 - name: Install-Jenkins
   hosts: jenkins
   gather_facts: false
   tasks:

    - name: Update
      apt:
       update_cache: true
    
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
    - name: Remove existing Jenkins repo configuration
      file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: absent
      ignore_errors: yes

    - name: Add Jenkins repository key
      shell: |
       wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add - 
       sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
     
    - name: Add Jenkins repository
      shell: |
       sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5BA31D57EF5975CA

    - name: Update package cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins package
      apt:
        name: jenkins
        state: "{{ state }}"

    - name: Start and enable Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes        

    - name: Wait for Jenkins to start up
      wait_for:
        port: 8080
        host: localhost
        delay: 30
        timeout: 300

    - name:  Get initialAdminPassword
      shell: |
       cat /var/lib/jenkins/secrets/initialAdminPassword
      register:   jenkins_initial_password
      ignore_errors: true

    - name: Print Jenkins initial admin password
      debug:
        msg: "initialAdminPasswordis: {{ jenkins_initial_password.stdout }}"

   handlers:
    - name: restart_jenkins
      service:
        name: jenkins
        state: restarted           



 - name: Install-Docker
   hosts: jenkins
   gather_facts: false
   tasks:
       
    - name: Update
      apt:
       update_cache: true
    
    - name: Install Docker
      apt:
        name: docker.io
        state: "{{state}}"

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add jenkins user to the docker group
      command: sudo usermod -aG docker jenkins

    - name: Add ubuntu to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Restart Docker to apply group changes
      systemd:
        name: docker
        state: restarted
